baseURL = "https://mkschleg.github.io"
languageCode = "en-us"
title = "Matthew Schlegel"
# author = "Matthew Schlegel"

theme = "minimal-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#preserveTaxonomyNames = true
paginate = 10

Copyright = "Copyright &#xA9; 2020 Matthew Schlegel. All Rights Reserved"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Get last modified date for content from Git?
enableGitInfo = false

[markup.goldmark.renderer]
  unsafe= true

[taxonomies]
  tag = "tags"
  collection = "collections"

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/readfiles/bfconfig/
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]
  # Your details.
  name = "Matthew Schlegel"
  bio = "Lover of Espresso; PhD student at Amii, RLAI and UofA; Works on how machines perceive their world."

  avatar = "me.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  avatar_coffee = "icon.png"

  location = "Edmonton, Alberta"

  # Discussion link (e.g. link to a forum, mailing list, or chat).
  #   Uncomment line below to use.
    # discussion = { name = "Discuss", url = "https://discourse.gohugo.io" }

  # Date and time format (refer to Go's date format: http://fuckinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "3:04 PM"

  # Display comment count? Requires commenting to be enabled.
  comment_count = true

  # Enable native social sharing buttons?
  sharing = true

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = false

  custom_css = ["header.css", "img.css", "braindump.css", "post.css"]

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/mkschleg"
    text = "LinkedIn"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/mattschleg"
    text = "Twitter"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/mkschleg"
    text = "Github"

  [[params.taxonomy]]
    icon = "tag"
    icon_pack = "fa"
    link = "/tags"
    text = "Tags"
    
  [[params.taxonomy]]
    icon = "folder"
    icon_pack = "fa"
    link = "/collections"
    text = "Collections"

  # Header menu links
  [[params.menu]]
    link = "/"
    text = "Home"

  [[params.menu]]
    link = "/about"
    text = "About"

  [[params.menu]]
    link = "/publications"
    text = "Publications"

  [[params.menu]]
    link = "/post"
    text = "Posts"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    simple = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

